Script started on Fri 23 Jan 2015 05:28:28 PM PST
~
cibar007@hammer $ cd rshell
~/rshell
cibar007@hammer $ make
cd src; make
make[1]: Entering directory `/home/csmajs/cibar007/rshell/src'
g++ rshell.cpp -Wall -Werror -ansi -pedantic
make[1]: Leaving directory `/home/csmajs/cibar007/rshell/src'
~/rshell
cibar007@hammer $ ./a.out
bash: ./a.out: No such file or directory
~/rshell
cibar007@hammer $ exit
exit

Script done on Fri 23 Jan 2015 05:29:08 PM PST
